# Generated by Django 3.1.5 on 2021-01-27 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chapter_title', models.CharField(blank=True, default='', max_length=200)),
                ('read_time', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Topic_title', models.CharField(blank=True, default='', max_length=200)),
                ('read_time', models.IntegerField(blank=True, default=0)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Course.chapter')),
            ],
        ),
    ]
