# Generated by Django 3.1.7 on 2021-02-22 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chapter',
            name='read_time',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='read_time',
        ),
        migrations.AddField(
            model_name='topic',
            name='have_checkpoint',
            field=models.BooleanField(default=False),
        ),
    ]
