# Generated by Django 3.1.5 on 2021-02-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_doyouknow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doyouknow',
            options={'verbose_name': 'Do You Know Note', 'verbose_name_plural': 'Do You Know Notes'},
        ),
    ]
