# Generated by Django 3.1.5 on 2021-02-01 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Course', '0002_auto_20210202_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='Div1',
        ),
        migrations.DeleteModel(
            name='Div2',
        ),
        migrations.DeleteModel(
            name='Div3',
        ),
        migrations.DeleteModel(
            name='ElementType',
        ),
    ]
