# Generated by Django 3.1.5 on 2021-02-11 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0003_auto_20210209_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_number',
            new_name='number',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='topic_number',
            new_name='number',
        ),
    ]
