# Generated by Django 3.1.5 on 2021-02-01 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Course', '0003_auto_20210202_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(('app_label', 'Course'), ('model', 'TopicElement')), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
