# Generated by Django 3.1.5 on 2021-02-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0004_comment_div1_elementtype_page'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapter',
            old_name='Chapter_title',
            new_name='chapter_title',
        ),
        migrations.RenameField(
            model_name='elementtype',
            old_name='liked_by',
            new_name='topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='Topic_title',
            new_name='topic_title',
        ),
    ]
