# Generated by Django 3.1.5 on 2021-02-01 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0005_auto_20210201_0721'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Div2',
        ),
        migrations.RenameModel(
            old_name='Page',
            new_name='Div3',
        ),
        migrations.RenameField(
            model_name='div2',
            old_name='h3',
            new_name='h2',
        ),
        migrations.RenameField(
            model_name='div3',
            old_name='h2',
            new_name='h3',
        ),
    ]
