# Generated by Django 3.1.5 on 2021-02-04 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_auto_20210202_0156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicelement',
            name='topic',
        ),
        migrations.DeleteModel(
            name='Element',
        ),
        migrations.DeleteModel(
            name='TopicElement',
        ),
    ]
