# Generated by Django 3.1.5 on 2021-02-01 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Course', '0007_auto_20210201_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementtype',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'Course'), ('model', 'Div1')), models.Q(('app_label', 'Course'), ('model', 'Div2')), models.Q(('app_label', 'Course'), ('model', 'Div3')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
