# Generated by Django 3.1.5 on 2021-02-01 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('Course', '0008_auto_20210201_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elementtype',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'Course'), ('model', 'div1')), models.Q(('app_label', 'Course'), ('model', 'div2')), models.Q(('app_label', 'Course'), ('model', 'div3')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
