# Generated by Django 3.1.5 on 2021-02-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterscore',
            name='cleared',
            field=models.BooleanField(default=False),
        ),
    ]
