# Generated by Django 3.1.5 on 2021-01-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='topic_completed',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
