# Generated by Django 3.1.5 on 2021-02-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_chapterscore_cleared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chapterscore',
            old_name='maximum_max',
            new_name='maximum_marks',
        ),
    ]
