# Generated by Django 3.1.7 on 2021-02-24 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210224_1105'),
        ('account', '0003_chapterscore_profile_user'),
        ('Course', '0002_auto_20210222_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapterscore',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.quiz'),
        ),
        migrations.AlterField(
            model_name='chapterscore',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.chapter'),
        ),
    ]
