# Generated by Django 3.1.5 on 2021-02-03 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0007_auto_20210202_0156'),
        ('account', '0003_auto_20210203_0028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChapterScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted', models.IntegerField(default=0)),
                ('maximum_max', models.IntegerField(default=0)),
                ('scored_max', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.chapter')),
                ('profile_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
            ],
        ),
    ]
