elements = [
    {
        "atomic_no": "1",
        "name": "Hydrogen",
        "symbol": "H",
        "block": "s",
        "atomic_mass": "1.01",
        "nn": "0",
        "np": "1",
        "ne": "1",
        "period": "1",
        "group": "1",
        "phase": "gas",
        "radioactive": "FALSE",
        "natural": "TRUE",
        "metal": "FALSE",
        "non_metal": "TRUE",
        "metalloid": "FALSE",
        "type": "Other Non Metal",
        "atomic_radius": "0.79",
        "electronegativity": "2.2",
        "first_ionization": "13.5984",
        "density": "0.0000899",
        "melting_point": "14.175",
        "boiling_point": "20.28",
        "isotrops": "3",
        "discoverer": "Cavendish",
        "year": "1766",
        "specific_heat": "14.304",
        "shells": "1",
        "valence": "1"
    },
    {
        "atomic_no": "2",
        "name": "Helium",
        "symbol": "He",
        "block": "s",
        "atomic_mass": "4",
        "nn": "2",
        "np": "2",
        "ne": "2",
        "period": "1",
        "group": "18",
        "phase": "gas",
        "radioactive": "FALSE",
        "natural": "TRUE",
        "metal": "FALSE",
        "non_metal": "TRUE",
        "metalloid": "FALSE",
        "type": "Noble Gas",
        "atomic_radius": "0.49",
        "electronegativity": "-1",
        "first_ionization": "24.5874",
        "density": "0.000179",
        "melting_point": "-1",
        "boiling_point": "4.22",
        "isotrops": "5",
        "discoverer": "Janssen",
        "year": "1868",
        "specific_heat": "5.193",
        "shells": "1",
        "valence": "-1"
    },
    {
        "atomic_no": "3",
        "name": "Lithium",
        "symbol": "Li",
        "block": "s",
        "atomic_mass": "6.94",
        "nn": "4",
        "np": "3",
        "ne": "3",
        "period": "2",
        "group": "1",
        "phase": "gas",
        "radioactive": "FALSE",
        "natural": "TRUE",
        "metal": "TRUE",
        "non_metal": "FALSE",
        "metalloid": "FALSE",
        "type": "Alkali Metal",
        "atomic_radius": "2.1",
        "electronegativity": "0.98",
        "first_ionization": "5.3917",
        "density": "0.534",
        "melting_point": "453.85",
        "boiling_point": "1615",
        "isotrops": "5",
        "discoverer": "Arfvedson",
        "year": "1817",
        "specific_heat": "3.582",
        "shells": "2",
        "valence": "1"
    },
    {
        "atomic_no": "4",
        "name": "Beryllium",
        "symbol": "Be",
        "block": "s",
        "atomic_mass": "9.01",
        "nn": "5",
        "np": "4",
        "ne": "4",
        "period": "2",
        "group": "2",
        "phase": "gas",
        "radioactive": "FALSE",
        "natural": "TRUE",
        "metal": "TRUE",
        "non_metal": "FALSE",
        "metalloid": "FALSE",
        "type": "Alkaline Earth Metal",
        "atomic_radius": "1.4",
        "electronegativity": "1.57",
        "first_ionization": "9.3227",
        "density": "1.85",
        "melting_point": "1560.15",
        "boiling_point": "2742",
        "isotrops": "6",
        "discoverer": "Vaulquelin",
        "year": "1798",
        "specific_heat": "1.825",
        "shells": "2",
        "valence": "2"
    },
    {
        "atomic_no": "11",
        "name": "Sodium",
        "symbol": "Na",
        "block": "s",
        "atomic_mass": "22.99",
        "nn": "12",
        "np": "11",
        "ne": "11",
        "period": "3",
        "group": "1",
        "phase": "gas",
        "radioactive": "FALSE",
        "natural": "TRUE",
        "metal": "TRUE",
        "non_metal": "FALSE",
        "metalloid": "FALSE",
        "type": "Alkali Metal",
        "atomic_radius": "2.2",
        "electronegativity": "0.93",
        "first_ionization": "5.1391",
        "density": "0.971",
        "melting_point": "371.15",
        "boiling_point": "1156",
        "isotrops": "7",
        "discoverer": "Davy",
        "year": "1807",
        "specific_heat": "1.228",
        "shells": "3",
        "valence": "1"
    },
    {
        "atomic_no": "12",
        "name": "Magnesium",
        "symbol": "Mg",
        "block": "s",
        "atomic_mass": "24.31",
        "nn": "12",
        "np": "12",
        "ne": "12",
        "period": "3",
        "group": "2",
        "phase": "gas",
        "radioactive": "FALSE",
        "natural": "TRUE",
        "metal": "TRUE",
        "non_metal": "FALSE",
        "metalloid": "FALSE",
        "type": "Alkaline Earth Metal",
        "atomic_radius": "1.7",
        "electronegativity": "1.31",
        "first_ionization": "7.6462",
        "density": "1.74",
        "melting_point": "923.15",
        "boiling_point": "1363",
        "isotrops": "8",
        "discoverer": "Black",
        "year": "1755",
        "specific_heat": "1.023",
        "shells": "3",
        "valence": "2"
    },
    {
        "atomic_no": "19",
        "name": "Potassium",
        "symbol": "K",
        "block": "s",
        "atomic_mass": "39.1",
        "nn": "20",
        "np": "19",
        "ne": "19",
        "period": "4",
        "group": "1",
        "phase": "solid",
        "radioactive": "FALSE",
        "natural": "TRUE",
        "metal": "TRUE",
        "non_metal": "FALSE",
        "metalloid": "FALSE",
        "type": "Alkali Metal",
        "atomic_radius": "2.8",
        "electronegativity": "0.82",
        "first_ionization": "4.3407",
        "density": "0.862",
        "melting_point": "336.5",
        "boiling_point": "1032",
        "isotrops": "10",
        "discoverer": "Davy",
        "year": "1807",
        "specific_heat": "0.757",
        "shells": "4",
        "valence": "1"
    },
    {
        "atomic_no": "20",
        "name": "Calcium",
        "symbol": "Ca",
        "block": "s",
        "atomic_mass": "40.08",
        "nn": "20",
        "np": "20",
        "ne": "20",
        "period": "4",
        "group": "2",
        "phase": "solid",
        "radioactive": "FALSE",
        "natural": "TRUE",
        "metal": "TRUE",
        "non_metal": "FALSE",
        "metalloid": "FALSE",
        "type": "Alkaline Earth Metal",
        "atomic_radius": "2.2",
        "electronegativity": "1",
        "first_ionization": "6.1132",
        "density": "1.54",
        "melting_point": "1112.15",
        "boiling_point": "1757",
        "isotrops": "14",
        "discoverer": "Davy",
        "year": "1808",
        "specific_heat": "0.647",
        "shells": "4",
        "valence": "2"
    },
    {
        "atomic_no": "37",
        "name": "Rubidium",
        "symbol": "Rb",
        "block": "s",
        "atomic_mass": "85.47",
        "nn": "48",
        "np": "37",
        "ne": "37",
        "period": "5",
        "group": "1",
        "phase": "solid",
        "radioactive": "FALSE",
        "natural": "TRUE",
        "metal": "TRUE",
        "non_metal": "FALSE",
        "metalloid": "FALSE",
        "type": "Alkali Metal",
        "atomic_radius": "3",
        "electronegativity": "0.82",
        "first_ionization": "4.1771",
        "density": "1.53",
        "melting_point": "312.79",
        "boiling_point": "961",
        "isotrops": "20",
        "discoverer": "Bunsen and Kirchoff",
        "year": "1861",
        "specific_heat": "0.363",
        "shells": "5",
        "valence": "1"
    },
    {
        "atomic_no": "38",
        "name": "Strontium",
        "symbol": "Sr",
        "block": "s",
        "atomic_mass": "87.62",
        "nn": "50",
        "np": "38",
        "ne": "38",
        "period": "5",
        "group": "2",
        "phase": "solid",
        "radioactive": "FALSE",
        "natural": "TRUE",
        "metal": "TRUE",
        "non_metal": "FALSE",
        "metalloid": "FALSE",
        "type": "Alkaline Earth Metal",
        "atomic_radius": "2.5",
        "electronegativity": "0.95",
        "first_ionization": "5.6949",
        "density": "2.64",
        "melting_point": "1042.15",
        "boiling_point": "1655",
        "isotrops": "18",
        "discoverer": "Davy",
        "year": "1808",
        "specific_heat": "0.301",
        "shells": "5",
        "valence": "2"
    },
    {
        "atomic_no": "55",
        "name": "Cesium",
        "symbol": "Cs",
        "block": "s",
        "atomic_mass": "132.91",
        "nn": "78",
        "np": "55",
        "ne": "55",
        "period": "6",
        "group": "1",
        "phase": "solid",
        "radioactive": "FALSE",
        "natural": "TRUE",
        "metal": "TRUE",
        "non_metal": "FALSE",
        "metalloid": "FALSE",
        "type": "Alkali Metal",
        "atomic_radius": "3.3",
        "electronegativity": "0.79",
        "first_ionization": "3.8939",
        "density": "1.87",
        "melting_point": "301.7",
        "boiling_point": "944",
        "isotrops": "22",
        "discoverer": "Bunsen and Kirchoff",
        "year": "1860",
        "specific_heat": "0.242",
        "shells": "6",
        "valence": "1"
    },
    {
        "atomic_no": "56",
        "name": "Barium",
        "symbol": "Ba",
        "block": "s",
        "atomic_mass": "137.33",
        "nn": "81",
        "np": "56",
        "ne": "56",
        "period": "6",
        "group": "2",
        "phase": "solid",
        "radioactive": "FALSE",
        "natural": "TRUE",
        "metal": "TRUE",
        "non_metal": "FALSE",
        "metalloid": "FALSE",
        "type": "Alkaline Earth Metal",
        "atomic_radius": "2.8",
        "electronegativity": "0.89",
        "first_ionization": "5.2117",
        "density": "3.59",
        "melting_point": "1002.15",
        "boiling_point": "2170",
        "isotrops": "25",
        "discoverer": "Davy",
        "year": "1808",
        "specific_heat": "0.204",
        "shells": "6",
        "valence": "2"
    },
    {
        "atomic_no": "87",
        "name": "Francium",
        "symbol": "Fr",
        "block": "s",
        "atomic_mass": "223",
        "nn": "136",
        "np": "87",
        "ne": "87",
        "period": "7",
        "group": "1",
        "phase": "solid",
        "radioactive": "TRUE",
        "natural": "TRUE",
        "metal": "TRUE",
        "non_metal": "FALSE",
        "metalloid": "FALSE",
        "type": "Alkali Metal",
        "atomic_radius": "0",
        "electronegativity": "0.7",
        "first_ionization": "4.0727",
        "density": "1.87",
        "melting_point": "300.15",
        "boiling_point": "950",
        "isotrops": "21",
        "discoverer": "Perey",
        "year": "1939",
        "specific_heat": "-1",
        "shells": "7",
        "valence": "1"
    },
    {
        "atomic_no": "88",
        "name": "Radium",
        "symbol": "Ra",
        "block": "s",
        "atomic_mass": "226",
        "nn": "138",
        "np": "88",
        "ne": "88",
        "period": "7",
        "group": "2",
        "phase": "solid",
        "radioactive": "TRUE",
        "natural": "TRUE",
        "metal": "TRUE",
        "non_metal": "FALSE",
        "metalloid": "FALSE",
        "type": "Alkaline Earth Metal",
        "atomic_radius": "0",
        "electronegativity": "0.9",
        "first_ionization": "5.2784",
        "density": "5.5",
        "melting_point": "973.15",
        "boiling_point": "2010",
        "isotrops": "15",
        "discoverer": "Pierre and Marie Curie",
        "year": "1898",
        "specific_heat": "-1",
        "shells": "7",
        "valence": "2"
    }
]
