# Generated by Django 3.1.5 on 2021-01-29 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('s', 's'), ('p', 'p'), ('d', 'd'), ('f', 'f')], max_length=30, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Block',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Group',
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Period',
            },
        ),
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atomic_number', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('symbol', models.CharField(blank=True, max_length=20, null=True)),
                ('atomic_mass', models.FloatField(blank=True, null=True)),
                ('nn', models.IntegerField(blank=True, null=True, verbose_name='No of Neutrons')),
                ('np', models.IntegerField(blank=True, null=True, verbose_name='No of Protons')),
                ('ne', models.IntegerField(blank=True, null=True, verbose_name='No of Electrons')),
                ('phase', models.CharField(choices=[('Solid', 'Solid'), ('Gas', 'Gas'), ('Liquid', 'Liquid'), ('Artificial', 'Artificial')], max_length=30)),
                ('radioactive', models.BooleanField(default=False)),
                ('natural', models.BooleanField(default=False)),
                ('metal', models.BooleanField(default=False)),
                ('nonmetal', models.BooleanField(default=False)),
                ('metalloid', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('Transition Metal', 'Transition Metal'), ('Actinide', 'Actinide'), ('Lanthanide', 'Lanthanide'), ('Transactinide', 'Transactinide'), ('Nonmetal', 'Nonmetal'), ('Metal', 'Metal'), ('Metalloid', 'Metalloid'), ('Noble Gas', 'Noble Gas'), ('Alkali Metal', 'Alkali Metal'), ('Alkaline Earth Metal', 'Alkaline Earth Metal'), ('Halogen', 'Halogen'), ('Not Defined', 'Not Defined')], max_length=30)),
                ('atomic_radius', models.FloatField(blank=True, null=True)),
                ('electronegativity', models.FloatField(blank=True, null=True)),
                ('first_ionization', models.FloatField(blank=True, null=True)),
                ('density', models.FloatField(blank=True, null=True)),
                ('melting_point', models.FloatField(blank=True, null=True)),
                ('boiling_point', models.FloatField(blank=True, null=True)),
                ('ns', models.IntegerField(blank=True, default=0, verbose_name='Number of Isotopes')),
                ('discovered_by', models.CharField(blank=True, default='', max_length=200)),
                ('year', models.IntegerField(blank=True, choices=[(1920, 1920), (1921, 1921), (1922, 1922), (1923, 1923), (1924, 1924), (1925, 1925), (1926, 1926), (1927, 1927), (1928, 1928), (1929, 1929), (1930, 1930), (1931, 1931), (1932, 1932), (1933, 1933), (1934, 1934), (1935, 1935), (1936, 1936), (1937, 1937), (1938, 1938), (1939, 1939), (1940, 1940), (1941, 1941), (1942, 1942), (1943, 1943), (1944, 1944), (1945, 1945), (1946, 1946), (1947, 1947), (1948, 1948), (1949, 1949), (1950, 1950), (1951, 1951), (1952, 1952), (1953, 1953), (1954, 1954), (1955, 1955), (1956, 1956), (1957, 1957), (1958, 1958), (1959, 1959), (1960, 1960), (1961, 1961), (1962, 1962), (1963, 1963), (1964, 1964), (1965, 1965), (1966, 1966), (1967, 1967), (1968, 1968), (1969, 1969), (1970, 1970), (1971, 1971), (1972, 1972), (1973, 1973), (1974, 1974), (1975, 1975), (1976, 1976), (1977, 1977), (1978, 1978), (1979, 1979), (1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021)], null=True, verbose_name='Year of Discovery')),
                ('specific_heat', models.FloatField(blank=True, null=True)),
                ('shells', models.IntegerField(blank=True, null=True, verbose_name='Number of Shells')),
                ('valence', models.IntegerField(blank=True, null=True)),
                ('block', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Element.block')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Element.group')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Element.period')),
            ],
        ),
    ]
