# Generated by Django 3.1.5 on 2021-01-29 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Element', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='element',
            old_name='nonmetal',
            new_name='non_metal',
        ),
    ]
