# Generated by Django 3.1.5 on 2021-02-09 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Element', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='exception',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='element',
            name='exception_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
