# Generated by Django 3.1.5 on 2021-02-08 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Element', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='color',
            field=models.CharField(blank=True, choices=[('Alkali Metal', '#ff6666'), ('Alkaline Earth Metal', '#fedead'), ('Transition Metal', '#ffc0bf'), ('Actinide', '#ff99cb'), ('Lanthanide', '#ffbffe'), ('Post Transition Metal', '#cccccc'), ('Other Non Metal', '#e8e8e8'), ('Metalloid', '#cccc9a'), ('Noble Gas', '#c1feff'), ('Halogen', '#f1ff90')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='element',
            name='_type',
            field=models.CharField(blank=True, choices=[('Alkali Metal', 'Alkali Metal'), ('Alkaline Earth Metal', 'Alkaline Earth Metal'), ('Transition Metal', 'Transition Metal'), ('Actinide', 'Actinide'), ('Lanthanide', 'Lanthanide'), ('Post Transition Metal', 'Post Transition Metal'), ('Other Non Metal', 'Other Non Metal'), ('Metalloid', 'Metalloid'), ('Noble Gas', 'Noble Gas'), ('Halogen', 'Halogen')], max_length=30, null=True),
        ),
    ]
