# Generated by Django 3.1.5 on 2021-01-30 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Element', '0002_auto_20210130_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ['atomic_number'], 'verbose_name': 'Periodic Table Elements', 'verbose_name_plural': 'Periodic Table Elements'},
        ),
        migrations.AlterField(
            model_name='element',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='Element.block'),
        ),
    ]
