# Generated by Django 3.1.5 on 2021-01-31 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Element', '0003_auto_20210130_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='block',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='Element.block'),
        ),
    ]
