# Generated by Django 3.1.5 on 2021-01-31 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Element', '0004_group_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='atomic_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
