# Generated by Django 3.1.5 on 2021-01-31 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Element', '0005_auto_20210131_2324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='element',
            unique_together={('atomic_number', 'group')},
        ),
    ]
