# Generated by Django 3.1.5 on 2021-02-04 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0008_auto_20210204_2336'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='quiz',
            new_name='quiz_topic',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='option1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='option2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='option3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='option4',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='QuizChapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Course.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quiz_chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='game.quizchapter'),
        ),
    ]
