# Generated by Django 3.1.5 on 2021-02-09 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_doyouknow'),
        ('game', '0002_auto_20210209_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiztopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz_chapter',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz_topic',
        ),
        migrations.AddField(
            model_name='question',
            name='chapter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Course.chapter'),
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='Course.topic'),
        ),
        migrations.DeleteModel(
            name='QuizChapter',
        ),
        migrations.DeleteModel(
            name='QuizTopic',
        ),
    ]
